# Generated by Django 5.2.9 on 2026-05-23 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('sensor_type', models.CharField(default='air_quality', max_length=100)),
                ('installation_date', models.DateTimeField()),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AQIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField()),
                ('predicted_aqi', models.IntegerField()),
                ('predicted_category', models.CharField(max_length=20)),
                ('co_predicted', models.FloatField(blank=True, null=True)),
                ('no2_predicted', models.FloatField(blank=True, null=True)),
                ('benzene_predicted', models.FloatField(blank=True, null=True)),
                ('temperature_predicted', models.FloatField(blank=True, null=True)),
                ('model_type', models.CharField(choices=[('moving_avg', 'Moving Average'), ('linear_regression', 'Linear Regression'), ('arima', 'ARIMA')], default='moving_avg', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'AQI Prediction',
                'verbose_name_plural': 'AQI Predictions',
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_aqi', 'High AQI'), ('pollutant_spike', 'Pollutant Spike'), ('unusual_pattern', 'Unusual Pattern'), ('maintenance_due', 'Maintenance Due')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('benzene', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('aqi', models.IntegerField(blank=True, null=True)),
                ('aqi_category', models.CharField(blank=True, max_length=20, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__d03b31_idx'), models.Index(fields=['-timestamp'], name='sensors_sen_timesta_557074_idx')],
            },
        ),
    ]
